local M = {}

M.highlights_base = function (colors)
  return {
    Normal = { fg = colors.foreground, bg = colors.background },
    StatusLineNC = { fg = colors.transparent, bg = colors.ruler },
    StatusLine = { fg = colors.foreground, bg = colors.ruler },
    SignColumn = { bold = true, bg = colors.ruler, fg = colors.ruler },
    MsgArea = { fg = colors.foreground, bg = colors.background },
    ModeMsg = { fg = colors.green },
    MsgSeparator = { fg = colors.foreground, bg = colors.background },
    -- SpellBad = { fg = colors.color2 },
    -- SpellCap = { fg = colors.color6 },
    -- SpellLocal = { fg = colors.color4 },
    -- SpellRare = { fg = colors.color6 },
    NormalNC = { fg = colors.foreground, bg = colors.background },
    Pmenu = { fg = colors.foreground, bg = colors.background },
    PmenuSel = { fg = colors.foreground, bg = colors.selection },
    PmenuSbar = { bg = colors.ruler, fg = colors.selection },
    PmenuThumb = { bg = colors.line },
    WildMenu = { fg = colors.foreground, bg = colors.selection },
    CursorLineNr = { bold = true, fg = colors.black, bg = colors.cursor },
    Comment = { fg = colors.comment },
    Folded = { fg = colors.comment, bg = colors.ruler },
    FoldColumn = { fg = colors.foreground, bg = colors.ruler },
    LineNr = { fg = colors.foreground, bg = colors.ruler },
    FloatBorder = { fg = colors.foreground },
    Whitespace = { fg = colors.ruler },
    VertSplit = { fg = colors.window, bg = colors.window },
    CursorLine = { bg = colors.cursorline },
    CursorColumn = { bg = colors.line },
    ColorColumn = { bg = colors.line },
    NormalFloat = { bg = colors.background },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.background },
    WarningMsg = { fg = colors.orange },
    DiffAdd = { bg = colors.green_dark },
    DiffChange = { bg = colors.blue_dark },
    DiffDelete = { bg = colors.red_dark },
    QuickFixLine = { bg = colors.selection },
    MatchParen = { bold = true, fg = colors.yellow },
    Cursor = { fg = colors.foreground, bg = colors.cursor },
    lCursor = { fg = colors.foreground, bg = colors.cursor },
    CursorIM = { fg = colors.foreground, bg = colors.cursor },
    TermCursor = { fg = colors.black, bg = colors.cursor },
    TermCursorNC = { fg = colors.black, bg = colors.cursor },
    Conceal = { fg = colors.color4, bg = colors.background },
    Directory = { fg = colors.foreground },
    SpecialKey = { fg = colors.sline },
    Title = { fg = colors.foreground },
    ErrorMsg = { fg = colors.red_light, bg = colors.background },
    Search = { bold = true, fg = colors.yellow },
    IncSearch = { bold = true, underline = true, fg = colors.yellow, sp = colors.yellow },
    HlSearchLens = { fg = colors.comment },
    HlSearchLensNear = { fg = colors.yellow },
    Substitute = { fg = colors.color3, bg = colors.color6 },
    MoreMsg = { fg = colors.green },
    Question = { fg = colors.green },
    -- EndOfBuffer = { fg = colors.background },
    EndOfBuffer = { fg = colors.blue_dark },
    NonText = { fg = colors.blue_dark },
    Variable = { fg = colors.blue },
    String = { fg = colors.orange },
    Character = { fg = colors.orange },
    Constant = { fg = colors.green },
    Number = { fg = colors.green },
    Boolean = { fg = colors.blue },
    Float = { fg = colors.green },
    Identifier = { fg = colors.blue },
    Function = { fg = colors.blue },
    Operator = { fg = colors.foreground },
    Type = { fg = colors.blue },
    StorageClass = { fg = colors.foreground },
    Structure = { fg = colors.blue },
    Typedef = { fg = colors.blue },
    Keyword = { fg = colors.blue },
    Statement = { fg = colors.foreground },
    Conditional = { fg = colors.blue },
    Repeat = { fg = colors.foreground },
    Label = { fg = colors.blue },
    Exception = { fg = colors.blue },
    Include = { fg = colors.green },
    PreProc = { fg = colors.color6 },
    Define = { fg = colors.green },
    Macro = { fg = colors.color6 },
    PreCondit = { fg = colors.foreground },
    Special = { fg = colors.foreground },
    SpecialChar = { fg = colors.orange },
    Tag = { fg = colors.color4 },
    Debug = { fg = colors.color1 },
    Delimiter = { fg = colors.foreground },
    SpecialComment = { fg = colors.color2 },
    Ignore = { fg = colors.color7, bg = colors.background },
    Todo = { fg = colors.yellow, bg = colors.transparent },
    Error = { bold = true, undercurl = true, fg = colors.red_light, sp = colors.red_light },
    TabLine = { fg = colors.color2, bg = colors.background },
    TabLineSel = { fg = colors.foreground, bg = colors.background },
    TabLineFill = { fg = colors.foreground, bg = colors.background },

    -- nvim-cmp
    CmpDocumentationBorder = { fg = colors.foreground, bg = colors.background },
    CmpItemAbbr = { fg = colors.foreground },
    CmpItemAbbrDeprecated = { strikethrough = true, fg = colors.comment },
    CmpItemAbbrMatch = { fg = colors.blue },
    -- CmpItemAbbrMatchFuzzy = { fg = colors.color7, bg = colors.background },
    -- CmpItemMenu = { fg = colors.color2, bg = colors.background },
    -- CmpItemKind = { fg = colors.color4, bg = colors.background },
    CmpItemKindVariable = { fg = colors.blue },
    CmpItemKindInterface = { fg = colors.aqua },
    CmpItemKindText = { fg = colors.orange },
    CmpItemKindFunction = { fg = colors.blue_dark },
    CmpItemKindKeyword = { fg = colors.blue_light },

    -- treesitter
    TSAttribute = { fg = colors.aqua },
    TSBoolean = { fg = colors.blue },
    TSCharacter = { fg = colors.orange },
    TSComment = { fg = colors.comment },
    commentTSConstant = { bold = true, fg = colors.comment },
    TSConditional = { fg = colors.blue },
    -- TSConstant = { fg = colors.foreground },
    TSConstant = { fg = colors.green },
    TSConstBuiltin = { fg = colors.green },
    TSConstMacro = { fg = colors.green },
    TSConstructor = { fg = colors.foreground },
    TSException = { fg = colors.blue },
    TSField = { fg = colors.green },
    TSFloat = { fg = colors.green },
    TSFunction = { fg = colors.foreground },
    TSFuncBuiltin = { fg = colors.blue },
    TSFuncMacro = { fg = colors.blue },
    TSInclude = { fg = colors.green },
    TSKeyword = { fg = colors.blue },
    TSKeywordFunction = { fg = colors.blue },
    TsKeywordOperator = { fg = colors.blue },
    TSKeywordReturn = { fg = colors.blue },
    TSLabel = { fg = colors.blue },
    TSMethod = { fg = colors.foreground },
    TSNamespace = { fg = colors.foreground },
    TSNumber = { fg = colors.green },
    TSParameter = { fg = colors.aqua },
    TSParameterReference = { fg = colors.color9 },
    TSProperty = { fg = colors.blue },
    TSPunctDelimiter = { fg = colors.foreground },
    TSPunctBracket = { fg = colors.bracket },
    TSPunctSpecial = { fg = colors.color7 },
    TSRepeat = { fg = colors.blue },
    TSString = { fg = colors.orange },
    TSStringRegex = { fg = colors.orange },
    TSStringEscape = { fg = colors.orange },
    TSStringSpecial = { fg = colors.orange },
    TSSymbol = { fg = colors.green },
    TSTag = { fg = colors.color4 },
    TSTagAttribute = { fg = colors.green },
    TSTagDelimiter = { fg = colors.foreground },
    TSText = { fg = colors.orange },
    TSStrong = { fg = colors.foreground },
    TSEmphasis = { italic = true, fg = colors.color7 },
    TSUnderline = { fg = colors.color5 },
    TSStrike = { fg = colors.color7 },
    TSTitle = { fg = colors.foreground },
    TSLiteral = { fg = colors.color2 },
    TSURI = { fg = colors.blue_light },
    TSMath = { fg = colors.green },
    TSTextReference = { fg = colors.color6 },
    TSEnvirontment = { fg = colors.color5 },
    TSEnvironmentName = { fg = colors.color3 },
    TSNote = { fg = colors.color8 },
    TSWarning = { fg = colors.yellow },
    TSDanger = { fg = colors.color8 },
    TSType = { fg = colors.foreground },
    TSTypeBuiltin = { fg = colors.blue },
    TSVariable = { fg = colors.foreground },
    TSVariableBuiltin = { fg = colors.blue },

    -- DAP
    DapBreakpoint = { bg = colors.red_dark },
    DapStopped = { bg = colors.green_dark },
    DapLogPoint = { bg = colors.blue_dark },
    DapBreakpointSign = { fg = colors.red_light, bg = colors.ruler },
    DapStoppedSign = { fg = colors.green, bg = colors.ruler },
    DapLogPointSign = { fg = colors.blue_light, bg = colors.ruler },

    -- Diagnostic
    DiagnosticError = { fg = colors.red_light },
    DiagnosticWarn = { fg = colors.yellow_light },
    DiagnosticInfo = { fg = colors.blue_dark },
    DiagnosticHint = { fg = colors.aqua },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red_light },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue_dark },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.aqua },
    DiagnosticSignError = { fg = colors.red, bg = colors.ruler },
    DiagnosticSignWarn = { fg = colors.yellow, bg = colors.ruler },
    DiagnosticSignInfo = { fg = colors.blue, bg = colors.ruler },
    DiagnosticSignHint = { fg = colors.aqua, bg = colors.ruler },

    -- LspTrouble
    LspTroubleText = { fg = colors.foreground },
    LspTroubleCount = { fg = colors.color6, bg = colors.foreground },
    LspTroubleNormal = { fg = colors.foreground, bg = colors.background },

    -- Illuminate
    illuminatedWord = { bg = colors.foreground },
    illuminatedCurWord = { bg = colors.foreground },

    -- diff
    diffAdded = { fg = colors.green_dark },
    diffRemoved = { fg = colors.red_dark },
    diffChanged = { fg = colors.blue_dark },
    diffOldFile = { fg = colors.color5 },
    diffNewFile = { fg = colors.color5 },
    diffFile = { fg = colors.comment },
    diffLine = { fg = colors.comment },
    diffIndexLine = { fg = colors.color6 },

    -- Neogit
    -- NeogitBranch = { fg = colors.color6 },
    -- NeogitRemote = { fg = colors.color6 },
    -- NeogitHunkHeader = { bg = colors.background, fg = colors.foreground },
    -- NeogitHunkHeaderHighlight = { bg = colors.comment, fg = colors.color7 },
    -- NeogitDiffContextHighlight = { bg = colors.background, fg = colors.foreground },
    -- NeogitDiffDeleteHighlight = { fg = colors.color1, bg = colors.background },
    -- NeogitDiffAddHighlight = { fg = colors.color4, bg = colors.background },

    -- GitGutter
    GitGutterAdd = { bold = true, fg = colors.green }, -- diff mode: Added line |diff.txt|
    GitGutterChange = { bold = true, fg = colors.blue_light }, -- diff mode: Changed line |diff.txt|
    GitGutterDelete = { bold = true, fg = colors.red_light }, -- diff mode: Deleted line |diff.txt|

    -- GitSigns
    GitSignsAdd = { bold = true, fg = colors.green }, -- diff mode: Added line |diff.txt|
    GitSignsChange = { bold = true, fg = colors.blue_light }, -- diff mode: Changed line |diff.txt|
    GitSignsDelete = { bold = true, fg = colors.red_light }, -- diff mode: Deleted line |diff.txt|

    -- Telescope
    TelescopeBorder = { fg = colors.foreground },
    TelescopeNormal = { fg = colors.foreground },
    TelescopeSelection = { fg = colors.foreground, bg = colors.selection },

    -- Indent Blank Line
    IndentBlanklineChar = { fg = colors.ruler },

    -- NERDTree
    NERDTreeDir = { bold = true, fg = colors.foreground },
    NERDTreeRO = { fg = colors.foreground },
    NERDTreeFile = { fg = colors.darkgrey },
    NERDTreeExecFile = { fg = colors.green },
    NERDTreeBookmark = { fg = colors.foreground },
    NERDTreeBookmarkName = { fg = colors.blue },
    NERDTreeBookmarksLeader = { fg = colors.background },
    NERDTreeDirSlash = { fg = colors.foreground },
    NERDTreeOpenable = { fg = colors.green },
    NERDTreeClosable = { fg = colors.green },
    NERDTreePart = { fg = colors.aqua },
    NERDTreeHelp = { fg = colors.comment },

    -- NvimTree
    NvimTreeNormal = { fg = colors.foreground, bg = colors.background },
    NvimTreeNormalNC = { fg = colors.foreground, bg = colors.background },
    NvimTreeRootFolder = { fg = colors.color1 },
    NvimTreeGitDirty = { fg = colors.color5 },
    NvimTreeGitNew = { fg = colors.color4 },
    NvimTreeGitDeleted = { fg = colors.color1 },
    NvimTreeSpecialFile = { fg = colors.color6 },
    NvimTreeIndentMarker = { fg = colors.color0 },
    NvimTreeImageFile = { fg = colors.foreground },
    NvimTreeSymlink = { fg = colors.color7 },
    NvimTreeFolderIcon = { fg = colors.color4, bg = colors.background },
    NvimTreeFolderName = { fg = colors.foreground },
    NvimTreeOpenedFolderName = { fg = colors.color2 },
    NvimTreeEmptyFolderName = { fg = colors.color2 },
    NvimTreeStatusLineNC = { bg = colors.background, fg = colors.transparent },

    -- LspSaga
    LspFloatWinNormal = { bg = colors.background },
    LspFloatWinBorder = { fg = colors.background },
    LspSagaBorderTitle = { fg = colors.color7 },
    LspSagaHoverBorder = { fg = colors.color7 },
    LspSagaRenameBorder = { fg = colors.color4 },
    LspSagaDefPreviewBorder = { fg = colors.color4 },
    LspSagaCodeActionBorder = { fg = colors.color7 },
    LspSagaFinderSelection = { fg = colors.color1 },
    LspSagaCodeActionTitle = { fg = colors.color7 },
    LspSagaCodeActionContent = { fg = colors.color6 },
    LspSagaSignatureHelpBorder = { fg = colors.color1 },
    ReferencesCount = { fg = colors.color6 },
    DefinitionCount = { fg = colors.color6 },
    DefinitionIcon = { fg = colors.color7 },
    ReferencesIcon = { fg = colors.color7 },
    TargetWord = { fg = colors.color7 },

    -- NeoVim
    healthError = { fg = colors.red },
    healthSuccess = { fg = colors.green },
    healthWarning = { fg = colors.orange },

    -- BufferLine
    BufferLineIndicatorSelected = { fg = colors.color2 },
    BufferLineFill = { fg = colors.background, bg = colors.background },

    -- Startify
    StartifyHeader = { bold = true, fg = colors.blue_light },
    StartifyPath = { italic = true, fg = colors.foreground },
    StartifySlash = { italic = true, fg = colors.darkgrey },
    StartifyFile = { italic = true, fg = colors.blue },
    StartifySpecial = { fg = colors.darkgrey },
    StartifySelect = { fg = colors.blue_light },
  }
end

return M
