local M = {}

M.highlights_base = function (colors)
  return {
    Normal = { fg = colors.foreground, bg = colors.background },
    StatusLineNC = { fg = colors.transparent, bg = colors.ruler },
    StatusLine = { fg = colors.foreground, bg = colors.ruler },
    SignColumn = { bold = true, bg = colors.ruler, fg = colors.ruler },
    MsgArea = { fg = colors.foreground, bg = colors.background },
    ModeMsg = { fg = colors.green },
    MsgSeparator = { fg = colors.foreground, bg = colors.background },
    SpellBad = { undercurl = true, sp = colors.red_light },
    SpellCap = { undercurl = true, sp = colors.aqua },
    SpellLocal = { undercurl = true, sp = colors.green },
    SpellRare = { undercurl = true, sp = colors.literal },
    NormalNC = { fg = colors.foreground, bg = colors.background },
    Pmenu = { fg = colors.foreground, bg = colors.background },
    PmenuSel = { fg = colors.foreground, bg = colors.selection },
    PmenuSbar = { bg = colors.ruler, fg = colors.selection },
    PmenuThumb = { bg = colors.line },
    WildMenu = { fg = colors.foreground, bg = colors.selection },
    CursorLineNr = { bold = true, fg = colors.black, bg = colors.cursor },
    Comment = { fg = colors.comment },
    Folded = { fg = colors.comment, bg = colors.ruler },
    FoldColumn = { fg = colors.foreground, bg = colors.ruler },
    LineNr = { fg = colors.foreground, bg = colors.ruler },
    FloatBorder = { fg = colors.foreground },
    FloatTitle = { fg = colors.green },
    NormalFloat = { bg = colors.background },
    Whitespace = { fg = colors.ruler },
    VertSplit = { fg = colors.window, bg = colors.transparent },
    CursorLine = { bg = colors.cursorline },
    CursorColumn = { bg = colors.line },
    ColorColumn = { bg = colors.line },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.background },
    WarningMsg = { fg = colors.orange },
    DiffAdd = { bg = colors.green_dark },
    DiffChange = { bg = colors.blue_dark },
    DiffDelete = { bg = colors.red_dark },
    QuickFixLine = { bg = colors.selection },
    MatchParen = { bold = true, fg = colors.yellow },
    Cursor = { fg = colors.foreground, bg = colors.cursor },
    iCursor = { fg = colors.foreground, bg = colors.cursor },
    lCursor = { fg = colors.foreground, bg = colors.cursor },
    CursorIM = { fg = colors.foreground, bg = colors.cursor },
    TermCursor = { fg = colors.black, bg = colors.cursor },
    TermCursorNC = { fg = colors.black, bg = colors.cursor },
    Conceal = { fg = colors.window, bg = colors.transparent },
    Directory = { fg = colors.foreground },
    SpecialKey = { fg = colors.sline },
    Title = { fg = colors.foreground },
    ErrorMsg = { fg = colors.red_light, bg = colors.background },
    Search = { bold = true, fg = colors.yellow },
    IncSearch = { bold = true, underline = true, fg = colors.yellow, sp = colors.yellow },
    HlSearchLens = { fg = colors.comment },
    HlSearchLensNear = { fg = colors.yellow },
    Substitute = { fg = colors.black, bg = colors.yellow },
    MoreMsg = { fg = colors.green },
    Question = { fg = colors.green },
    EndOfBuffer = { fg = colors.blue_dark },
    NonText = { fg = colors.blue_dark },
    Variable = { fg = colors.blue },
    String = { fg = colors.orange },
    Character = { fg = colors.orange },
    Constant = { fg = colors.green },
    Number = { fg = colors.green },
    Boolean = { fg = colors.blue },
    Float = { fg = colors.green },
    Identifier = { fg = colors.blue },
    Function = { fg = colors.blue },
    Operator = { fg = colors.foreground },
    Type = { fg = colors.blue },
    StorageClass = { fg = colors.foreground },
    Structure = { fg = colors.blue },
    Typedef = { fg = colors.blue },
    Keyword = { fg = colors.blue },
    Statement = { fg = colors.foreground },
    Conditional = { fg = colors.blue },
    Repeat = { fg = colors.foreground },
    Label = { fg = colors.blue },
    Exception = { fg = colors.blue },
    Include = { fg = colors.green },
    PreProc = { fg = colors.green }, -- TODO
    Define = { fg = colors.green },
    Macro = { fg = colors.blue }, -- TODO
    PreCondit = { fg = colors.foreground },
    Special = { fg = colors.foreground },
    SpecialChar = { fg = colors.orange },
    Tag = { fg = colors.blue },
    Debug = { fg = colors.red },
    Delimiter = { fg = colors.foreground },
    SpecialComment = { fg = colors.window },
    Ignore = { fg = colors.red, bg = colors.transparent },
    Todo = { fg = colors.yellow, bg = colors.transparent },
    Error = { bold = true, undercurl = true, fg = colors.red_light, sp = colors.red_light },
    TabLine = { fg = colors.foreground, bg = colors.window },
    TabLineSel = { fg = colors.foreground, bg = colors.background },
    TabLineFill = { fg = colors.foreground, bg = colors.background },
    Underlined = { underline = false, sp = colors.foreground },

    -- nvim-cmp
    CmpDocumentationBorder = { fg = colors.foreground, bg = colors.background },
    CmpItemAbbr = { fg = colors.foreground },
    CmpItemAbbrDeprecated = { strikethrough = true, fg = colors.comment },
    CmpItemAbbrMatch = { fg = colors.blue },
    CmpItemKindVariable = { fg = colors.blue },
    CmpItemKindInterface = { fg = colors.aqua },
    CmpItemKindText = { fg = colors.orange },
    CmpItemKindFunction = { fg = colors.blue_dark },
    CmpItemKindKeyword = { fg = colors.blue_light },

    -- treesitter
    TSAttribute = { fg = colors.foreground },
    TSBoolean = { fg = colors.blue },
    TSCharacter = { fg = colors.orange },
    TSComment = { fg = colors.comment },
    commentTSConstant = { bold = true, fg = colors.comment },
    TSConditional = { fg = colors.blue },
    TSConstant = { fg = colors.green },
    TSConstBuiltin = { fg = colors.green },
    TSConstMacro = { fg = colors.green },
    TSConstructor = { fg = colors.foreground },
    TSException = { fg = colors.blue },
    TSField = { fg = colors.green },
    TSFloat = { fg = colors.green },
    TSFunction = { fg = colors.foreground },
    TSFuncBuiltin = { fg = colors.blue },
    TSFuncMacro = { fg = colors.blue },
    TSInclude = { fg = colors.green },
    TSKeyword = { fg = colors.blue },
    TSKeywordFunction = { fg = colors.blue },
    TsKeywordOperator = { fg = colors.blue },
    TSKeywordReturn = { fg = colors.blue },
    TSLabel = { fg = colors.blue },
    TSMethod = { fg = colors.foreground },
    TSNamespace = { fg = colors.foreground },
    TSNumber = { fg = colors.green },
    TSParameter = { fg = colors.aqua },
    TSParameterReference = { fg = colors.red },
    TSProperty = { fg = colors.blue },
    TSPunctDelimiter = { fg = colors.foreground },
    TSPunctBracket = { fg = colors.bracket },
    TSPunctSpecial = { fg = colors.comment },
    TSRepeat = { fg = colors.blue },
    TSString = { fg = colors.orange },
    TSStringRegex = { fg = colors.orange },
    TSStringEscape = { fg = colors.orange },
    TSStringSpecial = { fg = colors.orange },
    TSSymbol = { fg = colors.green },
    TSTag = { fg = colors.blue },
    TSTagAttribute = { fg = colors.green },
    TSTagDelimiter = { fg = colors.foreground },
    TSText = { fg = colors.orange },
    TSStrong = { fg = colors.foreground },
    TSEmphasis = { italic = true },
    -- TSUnderline = { fg = colors.color5 },
    TSStrike = { fg = colors.foreground },
    TSTitle = { bold = true, fg = colors.foreground },
    TSLiteral = { fg = colors.literal },
    TSURI = { fg = colors.blue_light },
    TSMath = { fg = colors.green },
    TSTextReference = { fg = colors.blue_dark},
    TSEnvirontment = { fg = colors.green_dark },
    TSEnvironmentName = { fg = colors.literal },
    TSNote = { fg = colors.aqua },
    TSWarning = { fg = colors.yellow },
    TSDanger = { fg = colors.red_light },
    TSType = { fg = colors.foreground },
    TSTypeBuiltin = { fg = colors.blue },
    TSVariable = { fg = colors.foreground },
    TSVariableBuiltin = { fg = colors.blue },

    -- Dap
    DapBreakpoint = { bg = colors.red_dark },
    DapStopped = { bg = colors.green_dark },
    DapLogPoint = { bg = colors.blue_dark },
    DapBreakpointSign = { fg = colors.red_light, bg = colors.ruler },
    DapStoppedSign = { fg = colors.green, bg = colors.ruler },
    DapLogPointSign = { fg = colors.blue_light, bg = colors.ruler },
    NvimDapVirtualText = { fg = colors.aqua },

    -- DapUI
    DapUIVariable = { fg = colors.foreground, bg = colors.transparent },
    DapUIValue = { fg = colors.foreground, bg = colors.transparent },
    DapUIFrameName = { fg = colors.foreground, bg = colors.transparent },
    DapUIScope = { fg = colors.aqua },
    DapUIType = { fg = colors.blue },
    DapUIThread = { fg = colors.green },
    DapUIStoppedThread = { fg = colors.green, bg = colors.green_dark },
    DapUISource = { fg = colors.comment },
    DapUIWatchesEmpty = { fg = colors.red_light },
    DapUIWatchesValue = { fg = colors.green },
    DapUIWatchesError = { fg = colors.red_light },
    DapUIModifiedValue = { fg = colors.orange },
    DapUIBreakpointsPath = { fg = colors.foreground },
    DapUIBreakpointsInfo = { fg = colors.green_dark },
    DapUIBreakpointsCurrentLine = { fg = colors.green },
    DapUIBreakpointsDisabledLine = { fg = colors.comment },

--[[ TODO: Currently not used
    DapUIDecoration guifg=#00F1F5")
    DapUISource guifg=#D484FF")
    DapUILineNumber guifg=#00f1f5")
    DapUIFloatBorder guifg=#00F1F5")
]]

    -- Diagnostic
    DiagnosticError = { fg = colors.red_light },
    DiagnosticWarn = { fg = colors.yellow_light },
    DiagnosticInfo = { fg = colors.blue_dark },
    DiagnosticHint = { fg = colors.aqua },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red_light },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue_dark },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.aqua },
    DiagnosticSignError = { fg = colors.red_light, bg = colors.ruler },
    DiagnosticSignWarn = { fg = colors.yellow, bg = colors.ruler },
    DiagnosticSignInfo = { fg = colors.blue, bg = colors.ruler },
    DiagnosticSignHint = { fg = colors.aqua, bg = colors.ruler },

    LspInfoBorder = { fg = colors.foreground, bg = colors.transparent },

    -- LspTrouble
    LspTroubleText = { fg = colors.foreground },
    LspTroubleCount = { fg = colors.green_dark, bg = colors.foreground },
    LspTroubleNormal = { fg = colors.foreground, bg = colors.background },

    -- Illuminate
    illuminatedWord = { bg = colors.foreground },
    illuminatedCurWord = { bg = colors.foreground },

    -- Incline
    InclineNormal = { fg = colors.black, bg = colors.cursor },
    InclineNormalNC = { fg = colors.window, bg = colors.transparent },

    -- diff
    diffAdded = { fg = colors.green_dark },
    diffRemoved = { fg = colors.red_dark },
    diffChanged = { fg = colors.blue_dark },
    diffOldFile = { fg = colors.window },
    diffNewFile = { fg = colors.green },
    diffFile = { fg = colors.comment },
    diffLine = { fg = colors.comment },
    diffIndexLine = { fg = colors.line },

    -- Neogit
    NeogitHunkHeader = { bg = colors.ruler, fg = colors.foreground },
    NeogitHunkHeaderHighlight = { bg = colors.ruler, fg = colors.yellow },
    NeogitDiffContextHighlight = { bg = colors.background, fg = colors.foreground },
    NeogitDiffDeleteHighlight = { fg = colors.foreground, bg = colors.red_dark },
    NeogitDiffAddHighlight = { fg = colors.foreground, bg = colors.green_dark },

    -- GitGutter
    GitGutterAdd = { bold = true, fg = colors.green, bg = colors.ruler },
    GitGutterChange = { bold = true, fg = colors.blue_light, bg = colors.ruler },
    GitGutterDelete = { bold = true, fg = colors.red_light, bg = colors.ruler },

    -- GitSigns
    GitSignsAdd = { bold = true, fg = colors.green, bg = colors.ruler },
    GitSignsChange = { bold = true, fg = colors.blue_light, bg = colors.ruler },
    GitSignsDelete = { bold = true, fg = colors.red_light, bg = colors.ruler },

    -- Signify
    SignifySignAdd = { bold = true, fg = colors.green, bg = colors.ruler },
    SignifySignChange = { bold = true, fg = colors.blue_light, bg = colors.ruler },
    SignifySignDelete = { bold = true, fg = colors.red_light, bg = colors.ruler },

    -- Telescope
    TelescopeBorder = { fg = colors.foreground, bg = colors.transparent },
    TelescopeNormal = { fg = colors.foreground },
    TelescopeSelection = { fg = colors.foreground, bg = colors.selection },
    TelescopeTitle = { fg = colors.green },

    -- Indent Blank Line
    IndentBlanklineChar = { fg = colors.ruler },

    -- NERDTree
    NERDTreeDir = { bold = true, fg = colors.foreground },
    NERDTreeRO = { fg = colors.foreground },
    NERDTreeFile = { fg = colors.darkgrey },
    NERDTreeExecFile = { fg = colors.green },
    NERDTreeBookmark = { fg = colors.foreground },
    NERDTreeBookmarkName = { fg = colors.blue },
    NERDTreeBookmarksLeader = { fg = colors.background },
    NERDTreeDirSlash = { fg = colors.foreground },
    NERDTreeOpenable = { fg = colors.foreground },
    NERDTreeClosable = { fg = colors.foreground },
    NERDTreePart = { fg = colors.aqua },
    NERDTreeHelp = { fg = colors.comment },
    NERDTreeFlags = { fg = colors.comment },

    -- NvimTree
    NvimTreeNormal = { fg = colors.foreground, bg = colors.transparent },
    NvimTreeNormalNC = { fg = colors.foreground, bg = colors.transparent },
    NvimTreeRootFolder = { fg = colors.foreground },
    NvimTreeGitDirty = { fg = colors.orange },
    NvimTreeGitNew = { fg = colors.green },
    NvimTreeGitDeleted = { fg = colors.red },
    NvimTreeSpecialFile = { fg = colors.blue },
    NvimTreeIndentMarker = { fg = colors.foreground },
    NvimTreeImageFile = { fg = colors.foreground },
    NvimTreeSymlink = { fg = colors.aqua },
    NvimTreeFolderIcon = { fg = colors.comment },
    NvimTreeFolderName = { bold = true, fg = colors.foreground },
    NvimTreeOpenedFolderName = { bold = true, fg = colors.foreground },
    NvimTreeEmptyFolderName = { fg = colors.foreground },
    NvimTreeStatusLineNC = { bg = colors.background, fg = colors.transparent },
    NvimTreeVertSplit = { fg = colors.window, bg = colors.transparent },
    NvimTreeWinSeparator = { fg = colors.window, bg = colors.transparent },

    -- LightBulb
    LightBulbSign = { fg = colors.yellow_light, bg = colors.ruler },
    LightBulbVirtualText = { fg = colors.yellow_light, bg = colors.transparent },

    -- NeoVim
    healthError = { fg = colors.red },
    healthSuccess = { fg = colors.green },
    healthWarning = { fg = colors.orange },

    -- BufferLine
    BufferLineIndicatorSelected = { fg = colors.green },
    BufferLineFill = { fg = colors.background, bg = colors.background },

    -- Scrollbar
    ScrollbarHandle = { bg = colors.window },
    ScrollbarSearchHandle = { fg = colors.yellow, bg = colors.window },
    ScrollbarSearch = { fg = colors.yellow },
    ScrollbarErrorHandle = { fg = colors.red_light, bg = colors.window },
    ScrollbarError = { fg = colors.red_light },
    ScrollbarWarnHandle = { fg = colors.orange, bg = colors.window },
    ScrollbarWarn = { fg = colors.orange },
    ScrollbarInfoHandle = { fg = colors.blue_dark, bg = colors.window },
    ScrollbarInfo = { fg = colors.blue_dark },
    ScrollbarHintHandle = { fg = colors.aqua, bg = colors.window },
    ScrollbarHint = { fg = colors.aqua },
    ScrollbarMiscHandle = { fg = colors.foreground, bg = colors.window },
    ScrollbarMisc = { fg = colors.foreground },

    -- Startify
    StartifyHeader = { bold = true, fg = colors.blue_light },
    StartifyPath = { italic = true, fg = colors.foreground },
    StartifySlash = { italic = true, fg = colors.darkgrey },
    StartifyFile = { italic = true, fg = colors.blue },
    StartifySpecial = { fg = colors.darkgrey },
    StartifySelect = { fg = colors.blue_light },
  }
end

return M
